# Generated by Django 2.2 on 2019-12-06 12:53

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import s3_file_details.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filerecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to='')),
                ('filename', models.CharField(default=None, max_length=100, null=True)),
                ('filetype', models.CharField(default=None, max_length=100, null=True)),
                ('filename_Timestamp', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('RawFileRef_Id', models.CharField(default=None, max_length=100, null=True)),
                ('Action_Status', models.CharField(default=None, max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
                ('HQId', models.CharField(default=None, max_length=100, null=True)),
                ('GSTIN', models.CharField(default=None, max_length=100, null=True)),
                ('template_id', models.CharField(default=None, max_length=100, null=True)),
                ('sub_state', models.CharField(default=None, max_length=100, null=True)),
                ('stock_id', models.CharField(default=None, max_length=100, null=True)),
                ('Branch_id', models.CharField(default=None, max_length=100, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Uploaded_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('Uploadedtimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Merge_by', models.CharField(default=None, max_length=100, null=True)),
                ('Merge_Batch_Id', models.CharField(default=None, max_length=100, null=True)),
                ('Deleted_by', models.CharField(default=None, max_length=100, null=True)),
                ('Deleted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Archived_by', models.CharField(default=None, max_length=100, null=True)),
                ('processed_by', models.CharField(default=None, max_length=100, null=True)),
                ('raw_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('processed_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('error_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('control_summary_path', models.CharField(default=None, max_length=100, null=True)),
                ('Merge_file_path', models.CharField(default=None, max_length=100, null=True)),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('type', models.CharField(default=None, max_length=100, null=True)),
                ('financial_year', models.CharField(default=None, max_length=100, null=True)),
                ('month', models.CharField(default=None, max_length=100, null=True)),
                ('month2', models.CharField(default=None, max_length=100, null=True)),
                ('file_size', models.CharField(default=None, max_length=100, null=True)),
                ('status', models.CharField(default=None, max_length=100, null=True)),
                ('Merge_Reference', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Report_Type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Row_count', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Columns_count', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('GSTIN_count', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Unique_Invoice_Count', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Invoice_Value', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Taxable_Value', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('IGST', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('CGST', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('SGST_UTGST', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('CESS', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('reason', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Template_Name', models.CharField(default=None, max_length=100, null=True)),
                ('column_header', jsonfield.fields.JSONField(blank=True, null=True)),
                ('filename', models.CharField(default=None, max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('filename_Timestamp', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Type', models.CharField(default=None, max_length=100, null=True)),
                ('Action_Status', models.CharField(default=None, max_length=100, null=True)),
                ('Template_Type', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mastertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, storage=s3_file_details.models.OverwriteStorage(), upload_to='')),
                ('sheet_name', models.CharField(default=None, max_length=100, null=True)),
                ('row_no', models.CharField(default=None, max_length=100, null=True)),
                ('Company_Id', models.CharField(default=None, max_length=100, null=True)),
                ('Type', models.CharField(default=None, max_length=100, null=True)),
                ('file_size', models.CharField(default=None, max_length=100, null=True)),
                ('Uploadedtimestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Uploaded_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('filename_Timestamp', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('MasterFileColumns', models.TextField(default='Na')),
            ],
        ),
        migrations.CreateModel(
            name='TgComparisionandarithmeticandfuction2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_in', models.CharField(blank=True, db_column='Data_in', max_length=20, null=True)),
                ('new_column', models.CharField(blank=True, db_column='New_column', max_length=50, null=True)),
                ('rule_id', models.IntegerField(blank=True, db_column='Rule_id', null=True)),
                ('column_value', models.CharField(blank=True, db_column='Column_value', max_length=50, null=True)),
                ('header_col1', models.CharField(blank=True, db_column='Header_Col1', max_length=200, null=True)),
                ('oprator1', models.CharField(blank=True, db_column='Oprator1', max_length=50, null=True)),
                ('header_col2', models.CharField(blank=True, db_column='Header_Col2', max_length=200, null=True)),
                ('oprator2', models.CharField(blank=True, db_column='Oprator2', max_length=50, null=True)),
                ('values', models.CharField(blank=True, db_column='Values', max_length=50, null=True)),
                ('connector', models.CharField(blank=True, max_length=50, null=True)),
                ('set_value', models.CharField(blank=True, db_column='Set_value', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, db_column='Company_name', max_length=200, null=True)),
                ('companyid', models.IntegerField(blank=True, db_column='companyId', null=True)),
                ('template_name', models.CharField(blank=True, db_column='Template_Name', max_length=100, null=True)),
                ('master_id', models.CharField(blank=True, db_column='Master_id', max_length=10, null=True)),
                ('ruletype', models.CharField(blank=True, db_column='ruleType', max_length=20, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=35, null=True)),
                ('template', models.ForeignKey(blank=True, db_column='Template_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='s3_file_details.Mapping')),
            ],
        ),
    ]
