# Generated by Django 2.2 on 2019-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3_file_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgcomparisionandarithmeticandfuction2',
            name='set_value',
            field=models.CharField(blank=True, db_column='Set_value', max_length=200, null=True),
        ),
    ]
